version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - urlShortenerPgData:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-ns
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - .:/app
      - /app/node_modules
      - urlShortenerPgData:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  urlShortenerPgData:
